create table produse
(ID INT NOT NULL PRIMARY KEY,
DENUMIRE VARCHAR(40),
CANTITATE INT,
MAGAZIN INT,
FURNIZOR INT
)

drop table Catalin.dbo.BONURI

create table magazine
(ID INT NOT NULL PRIMARY KEY,
DENUMIRE VARCHAR(40),
ADRESA VARCHAR(20)
)

create table furnizori
(ID INT NOT NULL PRIMARY KEY,
DENUMIRE VARCHAR(40),
CONTRACT VARCHAR(20),
EXPIRARE_CONTRACT VARCHAR(40)
)

create table bonuri
(ID INT NOT NULL PRIMARY KEY,
MAGAZIN INT,
PRODUSE VARCHAR(20),
DATA DATETIME,
AMOUNT VARCHAR(20),
CASIER INT
)

create table CASIERI
(ID INT NOT NULL PRIMARY KEY,
NUMELE VARCHAR(40),
PRENUMELE VARCHAR(40),
DATA_NASTERII DATETIME,
MAGAZIN INT,
DATA_ANGAJARII DATETIME,
DATA_CREARE_CONTRACT DATETIME,
COD_SECTIE INT
)

create table SECTII_MAGAZIN
(ID INT NOT NULL PRIMARY KEY,
DENUMIRE VARCHAR(40),
SEF INT
)

create table SEFI
(ID INT NOT NULL PRIMARY KEY,
NUME VARCHAR(40),
PRENUME VARCHAR(20),
DATA_NASTERII DATETIME,
MAGAZIN VARCHAR(20),
DATA_INTRARE_FUNCTIE DATETIME
)